## import tkinter libraries to use 
import tkinter as tk
from tkinter import messagebox
from tkinter import *
from tkinter import ttk
import data as d
import plot as p
##import data

file1 = ''

##from data.py import process

## test script to test function of buttons
def testScript():
        messagebox.showinfo("Hello", "Wazzup")

def importFunction():
    file1 = d.importData()

def normaliseFunction():
    d.process(importFunction)

def importReadyDataFunction():
    p.importReadyData()

def plotFunction():
    p.plot(importReadyDataFunction)

## new tkinter window - labelled window
## title and size of window set
window = tk.Tk()
window.geometry("1080x720")
window.minsize(720, 400)
window.title("Raman Plotter")

## tabs will use notebook format
tabControl = ttk.Notebook(window)

## create layout for Raw Data tab - 2 panes flows vertically
## top row to hold buttons - 2 buttons flows horizontally
## bottom row to hold file list and preview of selected file - 2 panes flows horizonatally 
raw = ttk.PanedWindow(tabControl, orient=VERTICAL)
rawTop = ttk.PanedWindow(tabControl, orient=HORIZONTAL)
rawBottom = ttk.PanedWindow(tabControl, orient=HORIZONTAL, height=500)

## create layout for Ready Data tab - 2 panes flows vertically
## top row to hold buttons - 2 buttons flows horizontally
## bottom row to hold file list and preview of selected file - 2 panes flows horizonatally 
ready = ttk.PanedWindow(tabControl, orient=VERTICAL)
readyTop = ttk.PanedWindow(tabControl, orient=HORIZONTAL)
readyBottom = ttk.PanedWindow(tabControl, orient=HORIZONTAL, height=500)

## create layout for Plot tab - 1 Pane flows vertically
plot = ttk.PanedWindow(tabControl, orient=VERTICAL)

## create 3 tabs with titles for each stage of the data flow: Raw, Ready, Plot
## display tabs on window
tabControl.add(raw, text="Raw")
tabControl.add(ready, text="Ready")
tabControl.add(plot, text="Plot")
tabControl.pack(expand=1, fill="both")

## create buttons to import raw data files and normalise selected ready data files
## display buttons on raw tab (top row)
importRaw = Button(rawTop, text="Import Raw Data", width=20, height=2, command=importFunction, bg="blue", fg="white")
normaliseData = Button(rawTop, text="Normalise Data", width=20, height=2, command=normaliseFunction, bg="green", fg="white")
importRaw.pack(side=LEFT, padx=(20,10), pady=(10,0))
normaliseData.pack(side=LEFT, padx=(10,10), pady=(10,0))

## label and entry box prompts user to enter waveshift offset - this offset will be used in normalisation process
## pack entry box to RH side with appropriate padding
inputLabel = Label(rawTop, text="Enter Waveshift Offset: ")
rawInput = Entry(rawTop, width=20)
rawInput.pack(side=RIGHT, padx=(10,20), pady=(10,0))
inputLabel.pack(side=RIGHT, padx=(0,5), pady=(10,0))

## create pane to hold the file list and a pane to display a preview of a file when selected
rawFiles = Listbox(rawBottom, selectmode=MULTIPLE)
rawPreview = Listbox(rawBottom)

## scrollbar for file list on raw tab
rawScroll = Scrollbar(rawFiles)
rawScroll.pack(side=RIGHT, fill=Y)
rawFiles.config(yscrollcommand=rawScroll.set)
rawScroll.config(command=rawFiles.yview)

## scrollbar for preview list on raw tab
rawScroll2 = Scrollbar(rawPreview)
rawScroll2.pack(side=RIGHT, fill=Y)
rawPreview.config(yscrollcommand=rawScroll2.set)
rawScroll2.config(command=rawPreview.yview)

## demo data to populate file lists
for rawList in ["file1", "file2", "file3", "file4", "etc"]:
    rawFiles.insert(END, rawList)

## create buttons to import ready data files and plot selected ready data files
## display buttons on ready tab (top row)
importReady = Button(readyTop, text="Import Ready Data", width=20, height=2, command=importReadyDataFunction, bg="blue", fg="white")
plotData = Button(readyTop, text="Plot Data", width=20, height=2, command=plotFunction, bg="green", fg="white")
importReady.pack(side=LEFT, padx=(20,10), pady=(10,0))
plotData.pack(side=LEFT, padx=(10,10), pady=(10,0))

## create pane to hold the file list and a pane to display a preview of a file when selected
readyFiles = Listbox(readyBottom, selectmode=MULTIPLE, yscrollcommand=TRUE)
readyPreview = Listbox(readyBottom)

## scrollbar for file list on ready tab
readyScroll = Scrollbar(readyFiles)
readyScroll.pack(side=RIGHT, fill=Y)
readyFiles.config(yscrollcommand=readyScroll.set)
readyScroll.config(command=readyFiles.yview)

## scrollbar for preview list on ready tab
readyScroll2 = Scrollbar(readyPreview)
readyScroll2.pack(side=RIGHT, fill=Y)
readyPreview.config(yscrollcommand=readyScroll2.set)
readyScroll2.config(command=readyPreview.yview)

## demo data to populate file lists
for readyList in ["file1", "file2", "file3", "file4", "etc"]:
    readyFiles.insert(END, readyList)

## create single pane to display graph generated by the plot button function
plotPreview = Frame(plot, height=600)

## raw labels to hold details of developers and their contact details for support/enquiries
## pack labels to footer with appropriate padding
rawDev = Label(window, height=1, text="Developed by J.Perusic & J.Winter (2020)")
rawContact = Label(window, height=1, text="Contact the Developers at: example@example.com")
rawContact.pack(side=BOTTOM, pady=(5,5))
rawDev.pack(side=BOTTOM, pady=(0,0))

## add the created panes which hold and the top and bottom rows of the raw tab
## pack file list and preview panes to the raw tab
raw.add(rawTop)
raw.add(rawBottom)
rawFiles.pack(side=LEFT, expand=2, fill="both")
rawPreview.pack(side=RIGHT, expand=2, fill="both")

## pack file list and preview panes to the ready tab
## add the created panes which hold and the top and bottom rows of the ready tab
ready.add(readyTop)
ready.add(readyBottom)
readyFiles.pack(side=LEFT, expand=2, fill="both")
readyPreview.pack(side=RIGHT, expand=2, fill="both")

## add the created panes which holds the generated graph to the plot tab
plot.add(plotPreview)

## display the window on run
window.mainloop()