# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 364)
        Form.setStyleSheet("#label_header {\n"
"font: 16pt \"Courier\";\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_header = QtWidgets.QLabel(Form)
        self.label_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header.setObjectName("label_header")
        self.verticalLayout.addWidget(self.label_header)
        self.tab_widget_main = QtWidgets.QTabWidget(Form)
        self.tab_widget_main.setObjectName("tab_widget_main")
        self.tab_importer = QtWidgets.QWidget()
        self.tab_importer.setObjectName("tab_importer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_importer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table_files = QtWidgets.QTableWidget(self.tab_importer)
        self.table_files.setObjectName("table_files")
        self.table_files.setColumnCount(0)
        self.table_files.setRowCount(0)
        self.verticalLayout_2.addWidget(self.table_files)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_import = QtWidgets.QPushButton(self.tab_importer)
        self.btn_import.setObjectName("btn_import")
        self.horizontalLayout.addWidget(self.btn_import)
        self.btn_clear = QtWidgets.QPushButton(self.tab_importer)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout.addWidget(self.btn_clear)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tab_widget_main.addTab(self.tab_importer, "")
        self.tab_normalise = QtWidgets.QWidget()
        self.tab_normalise.setObjectName("tab_normalise")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_normalise)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_raw = QtWidgets.QLabel(self.tab_normalise)
        self.label_raw.setObjectName("label_raw")
        self.horizontalLayout_2.addWidget(self.label_raw)
        self.combo_raw = QtWidgets.QComboBox(self.tab_normalise)
        self.combo_raw.setObjectName("combo_raw")
        self.horizontalLayout_2.addWidget(self.combo_raw)
        self.label_param = QtWidgets.QLabel(self.tab_normalise)
        self.label_param.setObjectName("label_param")
        self.horizontalLayout_2.addWidget(self.label_param)
        self.edit_param = QtWidgets.QLineEdit(self.tab_normalise)
        self.edit_param.setObjectName("edit_param")
        self.horizontalLayout_2.addWidget(self.edit_param)
        self.btn_normalise = QtWidgets.QPushButton(self.tab_normalise)
        self.btn_normalise.setObjectName("btn_normalise")
        self.horizontalLayout_2.addWidget(self.btn_normalise)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.table_results = QtWidgets.QTableWidget(self.tab_normalise)
        self.table_results.setObjectName("table_results")
        self.table_results.setColumnCount(0)
        self.table_results.setRowCount(0)
        self.verticalLayout_3.addWidget(self.table_results)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tab_widget_main.addTab(self.tab_normalise, "")
        self.tab_plot = QtWidgets.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_plot)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_result = QtWidgets.QLabel(self.tab_plot)
        self.label_result.setObjectName("label_result")
        self.horizontalLayout_3.addWidget(self.label_result)
        self.combo_result = QtWidgets.QComboBox(self.tab_plot)
        self.combo_result.setObjectName("combo_result")
        self.horizontalLayout_3.addWidget(self.combo_result)
        self.btn_plot = QtWidgets.QPushButton(self.tab_plot)
        self.btn_plot.setObjectName("btn_plot")
        self.horizontalLayout_3.addWidget(self.btn_plot)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.graphics_view = CanvasWidget(self.tab_plot)
        self.graphics_view.setObjectName("graphics_view")
        self.verticalLayout_4.addWidget(self.graphics_view)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tab_widget_main.addTab(self.tab_plot, "")
        self.verticalLayout.addWidget(self.tab_widget_main)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tab_widget_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_header.setText(_translate("Form", "cRaman System"))
        self.btn_import.setText(_translate("Form", "Import"))
        self.btn_clear.setText(_translate("Form", "Clear"))
        self.tab_widget_main.setTabText(self.tab_widget_main.indexOf(self.tab_importer), _translate("Form", "Import Raw Data"))
        self.label_raw.setText(_translate("Form", "Choose Raw File"))
        self.label_param.setText(_translate("Form", "Wave Offset"))
        self.btn_normalise.setText(_translate("Form", "Normalise"))
        self.tab_widget_main.setTabText(self.tab_widget_main.indexOf(self.tab_normalise), _translate("Form", "Normalise"))
        self.label_result.setText(_translate("Form", "Choose Normalised Data"))
        self.btn_plot.setText(_translate("Form", "Plot"))
        self.tab_widget_main.setTabText(self.tab_widget_main.indexOf(self.tab_plot), _translate("Form", "Plot"))
from NEW_plot import CanvasWidget
